[celery]
broker="redis://localhost:6379/0"
backend="redis://localhost:6379/1"

[log]
# Available settings: single/daily
type="single"

# Available settings: debug/info/notice/warning/error/critical
level="debug"

# Available settings: file/stdout/stderr
driver="stderr"