[celery]
ENV='debug'

[log]
# Available settings: single/daily
type="single"

# Available settings: debug/info/notice/warning/error/critical
level="notice"

# Available settings: file/stdout/stderr
driver="stderr"